name: Acceptance Tests
on:
  push:
    branches:
      - master
jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Unshallow
        run: git fetch --prune --unshallow
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Run test
        run: make testacc
        env:
          GO_FLAGS: -mod=vendor
          GO111MODULE: on
          BRITIVE_TENANT: ${{ secrets.BRITIVE_TENANT }}
          BRITIVE_TOKEN: ${{ secrets.BRITIVE_TOKEN }}